### ISSUE TITLE
Is xdg-run/pipewire-0 needed?

### ISSUE THREAD

**Issue by spazziale** [flathub/org.gnome.Snapshot#27]
With it, Snapshot (or any other pipewire-based application) does not respect my privacy settings in the gnome settings. Removing  xdg-run/pipewire-0 solve the issue in Fedora 39

**Comment by A6GibKm** [comment]
Yes, its needed to use the unsandboxed camera in case the portal fails, due to a bug in dbus-proxy we need this fallback. We also need the sandbox hole for audio if I am not mistaken.

**Comment by spazziale** [comment]
Understandable, audio capture and playback work without xdg-run/pipewire-0 in Fedora 39
